### ISSUE TITLE
Alchemy error

### ISSUE THREAD

**Issue by janvsc** [pluralsight-projects/PythonFlask-CMSAuthentication#1]
After module 1 I did flask run and went to http://127.0.0.1:5000/admin/ and got this error:

File "C:\Python_Projects\authpy\venv\Lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: type
[SQL: SELECT type.id AS type_id, type.name AS type_name
FROM type]

I am stuck

**Comment by janvsc** [comment]
Found the answer

**Comment by 0lucian** [comment]
> 

Hi janvsc,
I am stuck in a similar error but for table content. Could you please share what was the solution you found?
Thanks
